### ISSUE TITLE
pystan==2.19.1.1 is not installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by zoglauer** [cositools/cosi-data-challenge-1#15]
Played a but with it: the latest version is installing, but not the desired one.

Error log:
Using legacy 'setup.py install' for pystan, since package 'wheel' is not installed.
Installing collected packages: webencodings, wcwidth, Send2Trash, pytz, pure-eval, ptyprocess, pickleshare, mistune, ipython-genutils, fastjsonschema, executing, backcall, appdirs, widgetsnbextension, websocket-client, traitlets, tqdm, tornado, tinycss2, soupsieve, sniffio, six, shapely, pyzmq, PyYAML, pyrsistent, pyparsing, pygments, pycparser, psutil, prompt-toolkit, prometheus-client, pillow, pexpect, parso, pandocfilters, numpy, nest-asyncio, multidict, markupsafe, kiwisolver, jupyterlab-widgets, jupyterlab-pygments, idna, frozenlist, fonttools, entrypoints, defusedxml, decorator, debugpy, Cython, cycler, charset-normalizer, attrs, async-timeout, yarl, terminado, scipy, python-dateutil, pystan, pyerfa, packaging, matplotlib-inline, jupyter-core, jsonschema, jinja2, jedi, emcee, contourpy, cffi, bleach, beautifulsoup4, asttokens, anyio, aiosignal, stack-data, qtpy, pandas, nbformat, matplotlib, marshmallow, jupyter-client, astropy, argon2-cffi-bindings, aiohttp, webargs, nbclient, ipython, corner, argon2-cffi, nbconvert, ipykernel, httpstan, qtconsole, jupyter-server, jupyter-console, ipywidgets, notebook-shim, nbclassic, notebook, jupyter
  Running setup.py install for pystan: started
  Running setup.py install for pystan: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for pystan did not run successfully.
  │ exit code: 1
  ╰─> [19284 lines of output]
      /tmp/pip-install-vcguvv5k/pystan_353ac03ed8f747a292e6eb4dc6289eb8/setup.py:235: DeprecationWarning:
      
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
      
      
        from numpy.distutils.command import install
      Compiling pystan/_api.pyx because it depends on /home/andreas/Science/Software/COSItools/p4/lib/python3.10/site-packages/Cython/Includes/libc/string.pxd.
      Compiling pystan/_chains.pyx because it depends on /home/andreas/Science/Software/COSItools/p4/lib/python3.10/site-packages/Cython/Includes/libc/math.pxd.
      [1/2] Cythonizing pystan/_chains.pyx
      [2/2] Cythonizing pystan/_api.pyx
      running install
      /home/andreas/Science/Software/COSItools/p4/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/pystan

...

      building 'pystan._misc' extension
      INFO: C compiler: x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
      
      INFO: compile options: '-I/home/andreas/Science/Software/COSItools/p4/include -I/usr/include/python3.10 -c'
      extra options: '-Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y'
      INFO: x86_64-linux-gnu-gcc: pystan/_misc.cpp
      In file included from /usr/include/python3.10/Python.h:74,
                       from pystan/_misc.cpp:24:
      pystan/_misc.cpp: In function ‘void __pyx_tp_dealloc_array(PyObject*)’:
      /usr/include/python3.10/object.h:133:33: error: lvalue required as increment operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:15723:7: note: in expansion of macro ‘Py_REFCNT’
      15723 |     ++Py_REFCNT(o);
            |       ^~~~~~~~~
      /usr/include/python3.10/object.h:133:33: error: lvalue required as decrement operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:15725:7: note: in expansion of macro ‘Py_REFCNT’
      15725 |     --Py_REFCNT(o);
            |       ^~~~~~~~~
      pystan/_misc.cpp: In function ‘void __pyx_tp_dealloc_memoryview(PyObject*)’:
      /usr/include/python3.10/object.h:133:33: error: lvalue required as increment operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:16018:7: note: in expansion of macro ‘Py_REFCNT’
      16018 |     ++Py_REFCNT(o);
            |       ^~~~~~~~~
      /usr/include/python3.10/object.h:133:33: error: lvalue required as decrement operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:16020:7: note: in expansion of macro ‘Py_REFCNT’
      16020 |     --Py_REFCNT(o);
            |       ^~~~~~~~~
      pystan/_misc.cpp: In function ‘void __pyx_tp_dealloc__memoryviewslice(PyObject*)’:
      /usr/include/python3.10/object.h:133:33: error: lvalue required as increment operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:16260:7: note: in expansion of macro ‘Py_REFCNT’
      16260 |     ++Py_REFCNT(o);
            |       ^~~~~~~~~
      /usr/include/python3.10/object.h:133:33: error: lvalue required as decrement operand
        133 | #define Py_REFCNT(ob) _Py_REFCNT(_PyObject_CAST_CONST(ob))
            |                       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:16262:7: note: in expansion of macro ‘Py_REFCNT’
      16262 |     --Py_REFCNT(o);
            |       ^~~~~~~~~
      In file included from /usr/include/python3.10/unicodeobject.h:1046,
                       from /usr/include/python3.10/Python.h:83,
                       from pystan/_misc.cpp:24:
      pystan/_misc.cpp: In function ‘int __Pyx_ParseOptionalKeywords(PyObject*, PyObject***, PyObject*, PyObject**, Py_ssize_t, const char*)’:
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        261 |       PyUnicode_WSTR_LENGTH(op) :                    \
            |       ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                      ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:262:33: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
            |              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                      ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
            |                                             ^~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        264 |        PyUnicode_WSTR_LENGTH(op)))
            |        ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                      ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        261 |       PyUnicode_WSTR_LENGTH(op) :                    \
            |       ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                    ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:262:33: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
            |              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                    ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
            |                                             ^~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        264 |        PyUnicode_WSTR_LENGTH(op)))
            |        ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18078:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18078 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                    ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        261 |       PyUnicode_WSTR_LENGTH(op) :                    \
            |       ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                          ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:262:33: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
            |              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                          ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
            |                                             ^~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        264 |        PyUnicode_WSTR_LENGTH(op)))
            |        ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                          ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        261 |       PyUnicode_WSTR_LENGTH(op) :                    \
            |       ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                           ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:262:33: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
            |              ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                           ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here
        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
            |                                             ^~~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:451:61: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
        451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
            |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
        264 |        PyUnicode_WSTR_LENGTH(op)))
            |        ^~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp:18094:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
      18094 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
            |                                                           ^~~~~~~~~~~~~~~~~~
      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
      pystan/_misc.cpp: In function ‘PyObject* __Pyx_decode_c_string(const char*, Py_ssize_t, Py_ssize_t, const char*, const char*, PyObject* (*)(const char*, Py_ssize_t, const char*))’:
      pystan/_misc.cpp:18596:37: warning: ‘PyObject* PyUnicode_FromUnicode(const Py_UNICODE*, Py_ssize_t)’ is deprecated [-Wdeprecated-declarations]
      18596 |         return PyUnicode_FromUnicode(NULL, 0);
            |                ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
      In file included from /usr/include/python3.10/unicodeobject.h:1046,
                       from /usr/include/python3.10/Python.h:83,
                       from pystan/_misc.cpp:24:
      /usr/include/python3.10/cpython/unicodeobject.h:551:42: note: declared here
        551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(
            |                                          ^~~~~~~~~~~~~~~~~~~~~
      error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/home/andreas/Science/Software/COSItools/p4/include -I/usr/include/python3.10 -c pystan/_misc.cpp -o build/temp.linux-x86_64-3.10/pystan/_misc.o -Os -ftemplate-depth-256 -Wno-unused-function -Wno-uninitialized -std=c++1y" failed with exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pystan

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by ckarwin** [comment]
Unfortunately, the latest version is not back-compatible with previous versions. 
Stan is part of COSIpy classic, but we plan to move away from it for the new COSIpy. 
Have you tried: conda install -c conda-forge pystan=2.19.1.1?

**Comment by ckarwin** [comment]
The following has been added to "Bug Report" in the main README:
COSIpy classic requires pystan version 2.19.1.1., which has compatibility issues with Ubuntu 22.04 and currently cannot be installed. This only impacts the imaging notebooks with the simulated data. They can still be ran without modification, and will produce qualitatively similar images for the point sources and 511; however, the Al26 notebook will not work without pytan. In order to install COSITools on Ubuntu 22.04 you must remove pystan from requirements.txt.
