### ISSUE TITLE
Viewing spectral-fit plots

### ISSUE THREAD

**Issue by jtomsick** [cositools/cosi-data-challenge-1#20]
When I click on the .png files in the spectral-fit/plots directory, they are extremely zoomed in.  I can download them to see them, but I do not see a way to view them at a viewable size in the browser.

**Comment by ckarwin** [comment]
Thanks for pointing this out. The plots directory was really only intended to store the images used in the README. I've now imbedded the images directly into the readme, and removed the plots directory. There was a reference to the plots directory in the text, but I've removed that as well, and instead refer directly to the corresponding image in the README.
