### ISSUE TITLE
Failure building wheel for pystan

### ISSUE THREAD

**Issue by jtomsick** [cositools/cosi-data-challenge-1#21]
My notes leading to a pystan error are below.  Possibly, this is related to the other pystan issue that was previously reported.  I'm also wondering if I did the right thing by running pip install on the requirements.txt file in the cosi-data-challenge-1 folder.

------

(python-env) johntomsick@Johns-MacBook-Pro COSItools % git clone https://github.com/cositools/cosi-data-challenge-1.git
(this takes several minutes)

(python-env) johntomsick@Johns-MacBook-Pro cosi-data-challenge-1 % cd cosi-data-challenge-1

(python-env) johntomsick@Johns-MacBook-Pro cosi-data-challenge-1 % pip install -r requirements.txt

...
Downloading jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Downloading uri_template-1.3.0-py3-none-any.whl (11 kB)
Building wheels for collected packages: pystan
  Building wheel for pystan (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      Cython>=0.22 and NumPy are required.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pystan
  Running setup.py clean for pystan
Failed to build pystan
ERROR: Could not build wheels for pystan, which is required to install pyproject.toml-based projects

**Comment by ckarwin** [comment]
This sounds similar to the other pystan issue. We have a note about this in the bug report at the bottom of the main readme. pystan is essentially only needed for the Al26 imaging. Otherwise, you can just remove it from the requirements.txt file, and then "pip install requirements.txt" should run ok. 

Please let me know if this solves the problem.

**Comment by jtomsick** [comment]
Yes, the "pip install requirements.txt" step worked after I removed the pystan line from requirements.txt.
